basePath: /
definitions:
  handlers.HealthResponse:
    properties:
      status:
        type: string
    type: object
  handlers.SearchInput:
    properties:
      artists:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  handlers.SearchResponse:
    properties:
      input:
        $ref: '#/definitions/handlers.SearchInput'
      video:
        $ref: '#/definitions/handlers.SearchVideo'
    type: object
  handlers.SearchVideo:
    properties:
      id:
        type: string
      url:
        type: string
    type: object
host: localhost:9898
info:
  contact: {}
  description: API for searching YouTube music videos
  title: YouTube Music Video API
  version: "1.0"
paths:
  /health:
    get:
      description: Returns the health status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
      summary: Health check endpoint
      tags:
      - health
  /search:
    get:
      description: Returns a list of music video search results
      parameters:
      - description: Title to search for
        in: query
        name: title
        required: true
        type: string
      - description: Artist name or comma-separated list of artists
        in: query
        name: artists
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SearchResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search for music videos
      tags:
      - search
swagger: "2.0"
